language: php
php:
    - 5.4
    - 5.5
    - 5.6
    - hhvm

before_script:
    - composer install --prefer-dist --dev

script:
    - composer validate
    - ./vendor/bin/phpunit
    - ./vendor/bin/phpcs --standard=PSR2 --encoding=utf-8 -p src/ tests/

matrix:
    allow_failures:
        - php: hhvm
    fast_finish: true
